### ISSUE TITLE
Implement new emoji that use ZWJ

### ISSUE THREAD

**Issue by samanthamjohn** [devongovett/apple-color-emoji#4]
http://unicode.org/emoji/charts/emoji-released.html

**Comment by devongovett** [comment]
Yeah this is getting more complex as more sequences are added. My plan is to use this: https://github.com/devongovett/fontkit/pull/60. It will allow getting strings from glyphs, so we can just loop over all glyphs in the font and get all the strings that generate them. Will hopefully have a release out in the next few days.

**Comment by samanthamjohn** [comment]
Great to hear! Gonna try it locally now.

**Comment by devongovett** [comment]
Merged #5. Published in v1.0.0!

**Comment by samanthamjohn** [comment]
🦄👨🏻‍⚕️
